# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rename` gem.
# Please instead update this file by running `bin/tapioca gem rename`.

# source://rename//lib/rename.rb#1
module Rename; end
